language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-wheel
      - clang-format-5.0
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.13"
     - PRETTYNAME="Google Cloud IoT Arduino Library"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
  - source $TRAVIS_BUILD_DIR/install.sh

install:
   - arduino --install-library "MQTT","WiFi101","DHT sensor library","Adafruit Unified Sensor"
script:
   - build_main_platforms

